blank_issues_enabled: true
contact_links:
  - name: Instrukcja instalacji i konfiguracji
    url: https://github.com/CyberGuard-PS/ha-gdzie-sie-ukryc
    about: Sprawdź README przed zgłoszeniem błędu.
